language: python
python:
  - "3.5"
install: "pip install -r requirements.txt"
script:
  - pip install coverage
  - coverage run manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
