version: "2"

services:

  db:
    container_name: db
    image: postgres:9.6.1
    environment:
      - POSTGRES_PASSWORD=controk_pass
      - POSTGRES_USER=controk_user
      - POSTGRES_DB=controk_db

  webservice:
    container_name: webservice
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    environment:
      - DATABASE_URL=postgres://controk_user:controk_pass@db/controk_db
      - ALLOWED_HOSTS=*
    links:
      - db

  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: ./nginx/Dockerfile
    links:
      - webservice
    ports:
      - "8000:8000"